### ISSUE TITLE
blog preview card - accessibility report

### ISSUE THREAD

**Issue by fermop** [fermop/frontend_mentor#11]
# Page should contain a level-one heading
Frontend Mentor generated a report to resolve errors and warnings. This error was generated because there is no level-one heading.

Taking into account that the card is a component of a web page, there has to be a level-one heading into the page.

In order to fix this issue follow the following steps:

## 1. Make changes into the right directory
The files that you have to modify are the _index.html_ and _styles.css_ that are in the following routes:
- _newbie/blog_preview_card/index.html_
- _newbie/blog_preview_card/css/styles.css_

## 2. Add a level-one heading with the class `sr-only` into the _index.html_.
We will add an `h1` that has no content for the user, due to it is only for screen readers.

```html
<body>
    <main class="card">
        <h1 class="sr-only">3-column preview card component</h1> <----
        <img class="card__img" src="./assets/images/illustration-article.svg" alt="Ilustration">
        <p class="card__category">Learning</p>
        <p class="card__published-date">Published 21 Dec 2023</p>
        <h2 class="card__title"><a href="#">HTML & CSS foundations</a></h2>
```

## 3. Add the specified styles for the class `.sr-only` into the _styles.css_.
Add the following styles in order to hide this `h1`:

```css
.sr-only:not(:focus):not(:active) {
        clip: rect(0 0 0 0); 
        clip-path: inset(50%);
        height: 0.0625rem;
        overflow: hidden;
        position: absolute;
        white-space: nowrap; 
        width: 0.0625rem;
}
```
